// Code generated by protoc-gen-go.
// source: discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	discovery.proto

It has these top-level messages:
	DfsServer
	DfsClient
	GetDfsServersReq
	GetDfsServersRep
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DfsServer_Status int32

const (
	DfsServer_ONLINE  DfsServer_Status = 0
	DfsServer_USED    DfsServer_Status = 1
	DfsServer_GOAWAY  DfsServer_Status = 2
	DfsServer_OFFLINE DfsServer_Status = 3
)

var DfsServer_Status_name = map[int32]string{
	0: "ONLINE",
	1: "USED",
	2: "GOAWAY",
	3: "OFFLINE",
}
var DfsServer_Status_value = map[string]int32{
	"ONLINE":  0,
	"USED":    1,
	"GOAWAY":  2,
	"OFFLINE": 3,
}

func (x DfsServer_Status) String() string {
	return proto.EnumName(DfsServer_Status_name, int32(x))
}

// Dfs Server
type DfsServer struct {
	Id     string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Uri    string           `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
	Weight int32            `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Load   int32            `protobuf:"varint,4,opt,name=load" json:"load,omitempty"`
	Free   int64            `protobuf:"varint,5,opt,name=free" json:"free,omitempty"`
	Status DfsServer_Status `protobuf:"varint,6,opt,name=status,enum=discovery.DfsServer_Status" json:"status,omitempty"`
}

func (m *DfsServer) Reset()         { *m = DfsServer{} }
func (m *DfsServer) String() string { return proto.CompactTextString(m) }
func (*DfsServer) ProtoMessage()    {}

// DfsClient represents client info.
type DfsClient struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Uri string `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
}

func (m *DfsClient) Reset()         { *m = DfsClient{} }
func (m *DfsClient) String() string { return proto.CompactTextString(m) }
func (*DfsClient) ProtoMessage()    {}

// The request message to get dfs server list.
type GetDfsServersReq struct {
	Client *DfsClient `protobuf:"bytes,1,opt,name=client" json:"client,omitempty"`
}

func (m *GetDfsServersReq) Reset()         { *m = GetDfsServersReq{} }
func (m *GetDfsServersReq) String() string { return proto.CompactTextString(m) }
func (*GetDfsServersReq) ProtoMessage()    {}

func (m *GetDfsServersReq) GetClient() *DfsClient {
	if m != nil {
		return m.Client
	}
	return nil
}

// The reply message to get dfs server list.
type GetDfsServersRep struct {
	Server *DfsServer `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
}

func (m *GetDfsServersRep) Reset()         { *m = GetDfsServersRep{} }
func (m *GetDfsServersRep) String() string { return proto.CompactTextString(m) }
func (*GetDfsServersRep) ProtoMessage()    {}

func (m *GetDfsServersRep) GetServer() *DfsServer {
	if m != nil {
		return m.Server
	}
	return nil
}

func init() {
	proto.RegisterEnum("discovery.DfsServer_Status", DfsServer_Status_name, DfsServer_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for DiscoveryService service

type DiscoveryServiceClient interface {
	// To get sever list by dfs client.
	GetDfsServers(ctx context.Context, in *GetDfsServersReq, opts ...grpc.CallOption) (DiscoveryService_GetDfsServersClient, error)
}

type discoveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryServiceClient(cc *grpc.ClientConn) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) GetDfsServers(ctx context.Context, in *GetDfsServersReq, opts ...grpc.CallOption) (DiscoveryService_GetDfsServersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DiscoveryService_serviceDesc.Streams[0], c.cc, "/discovery.DiscoveryService/GetDfsServers", opts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryServiceGetDfsServersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiscoveryService_GetDfsServersClient interface {
	Recv() (*GetDfsServersRep, error)
	grpc.ClientStream
}

type discoveryServiceGetDfsServersClient struct {
	grpc.ClientStream
}

func (x *discoveryServiceGetDfsServersClient) Recv() (*GetDfsServersRep, error) {
	m := new(GetDfsServersRep)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DiscoveryService service

type DiscoveryServiceServer interface {
	// To get sever list by dfs client.
	GetDfsServers(*GetDfsServersReq, DiscoveryService_GetDfsServersServer) error
}

func RegisterDiscoveryServiceServer(s *grpc.Server, srv DiscoveryServiceServer) {
	s.RegisterService(&_DiscoveryService_serviceDesc, srv)
}

func _DiscoveryService_GetDfsServers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDfsServersReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServiceServer).GetDfsServers(m, &discoveryServiceGetDfsServersServer{stream})
}

type DiscoveryService_GetDfsServersServer interface {
	Send(*GetDfsServersRep) error
	grpc.ServerStream
}

type discoveryServiceGetDfsServersServer struct {
	grpc.ServerStream
}

func (x *discoveryServiceGetDfsServersServer) Send(m *GetDfsServersRep) error {
	return x.ServerStream.SendMsg(m)
}

var _DiscoveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDfsServers",
			Handler:       _DiscoveryService_GetDfsServers_Handler,
			ServerStreams: true,
		},
	},
}
